# Generated by Django 3.1.7 on 2021-03-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookmodel',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
